<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Hands-on Lab : Web Scraping**

Estimated time needed: **30 to 45** minutes

## Objectives

In this lab you will perform the following:

* Extract information from a given web site
* Write the scraped data into a csv file.

## Extract information from the given web site
You will extract the data from the below web site: <br>

In [ ]:
#this url contains the data you need to scrape
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/labs/datasets/Programming_Languages.html"

The data you need to scrape is the **name of the programming language** and **average annual salary**.<br> It is a good idea to open the url in your web broswer and study the contents of the web page before you start to scrape.

Import the required libraries

In [ ]:
# Your code here
import requests
from bs4 import BeautifulSoup
import pandas as pd

Download the webpage at the url

In [ ]:
#your code goes here
data = requests.get(url).text

Create a soup object

In [ ]:
#your code goes here
soup = BeautifulSoup(data,'html.parser')

In [ ]:
beautify = soup.prettify()
print(beautify)

<!DOCTYPE html>
<html lang="en">
 <head>
  <title>
   Salary survey results of programming languages
  </title>
  <style>
   table, th, td {
  border: 1px solid black;
}
  </style>
 </head>
 <body>
  <hr/>
  <h2>
   Popular Programming Languages
  </h2>
  <hr/>
  <p>
   Finding out which is the best language is a tough task. A programming language is created to solve a specific problem. A language which is good for task A may not be able to properly handle task B. Comparing programming language is never easy. What we can do, however, is find which is popular in the industry.
  </p>
  <p>
   There are many ways to find the popularity of a programming languages. Counting the number of google searchs for each language is a simple way to find the popularity. GitHub and StackOverflow also can give some good pointers.
  </p>
  <p>
   Salary surveys are a way to find out the programmings languages that are most in demand in the industry. Below table is the result of one such survey. When using any survey keep in mind that the results vary year on year.
  </p>
  <hr/>
  <table>
   <tbody>
    <tr>
     <td>
      No.
     </td>
     <td>
      Language
     </td>
     <td>
      Created By
     </td>
     <td>
      Average Annual Salary
     </td>
     <td>
      Learning Difficulty
     </td>
    </tr>
    <tr>
     <td>
      1
     </td>
     <td>
      Python
     </td>
     <td>
      Guido van Rossum
     </td>
     <td>
      $114,383
     </td>
     <td>
      Easy
     </td>
    </tr>
    <tr>
     <td>
      2
     </td>
     <td>
      Java
     </td>
     <td>
      James Gosling
     </td>
     <td>
      $101,013
     </td>
     <td>
      Easy
     </td>
    </tr>
    <tr>
     <td>
      3
     </td>
     <td>
      R
     </td>
     <td>
      Robert Gentleman, Ross Ihaka
     </td>
     <td>
      $92,037
     </td>
     <td>
      Hard
     </td>
    </tr>
    <tr>
     <td>
      4
     </td>
     <td>
      Javascript
     </td>
     <td>
      Netscape
     </td>
     <td>
      $110,981
     </td>
     <td>
      Easy
     </td>
    </tr>
    <tr>
     <td>
      5
     </td>
     <td>
      Swift
     </td>
     <td>
      Apple
     </td>
     <td>
      $130,801
     </td>
     <td>
      Easy
     </td>
    </tr>
    <tr>
     <td>
      6
     </td>
     <td>
      C++
     </td>
     <td>
      Bjarne Stroustrup
     </td>
     <td>
      $113,865
     </td>
     <td>
      Hard
     </td>
    </tr>
    <tr>
     <td>
      7
     </td>
     <td>
      C#
     </td>
     <td>
      Microsoft
     </td>
     <td>
      $88,726
     </td>
     <td>
      Hard
     </td>
    </tr>
    <tr>
     <td>
      8
     </td>
     <td>
      PHP
     </td>
     <td>
      Rasmus Lerdorf
     </td>
     <td>
      $84,727
     </td>
     <td>
      Easy
     </td>
    </tr>
    <tr>
     <td>
      9
     </td>
     <td>
      SQL
     </td>
     <td>
      Donald D. Chamberlin, Raymond F. Boyce.
     </td>
     <td>
      $84,793
     </td>
     <td>
      Easy
     </td>
    </tr>
    <tr>
     <td>
      10
     </td>
     <td>
      Go
     </td>
     <td>
      Robert Griesemer, Ken Thompson, Rob Pike.
     </td>
     <td>
      $94,082
     </td>
     <td>
      Difficult
     </td>
    </tr>
   </tbody>
  </table>
  <hr/>
 </body>
</html>

In [ ]:
# #your code goes here
# Programming_Languages = pd.DataFrame(columns=['Language name','annual average salary'])
# table = soup.find('table')
# # print(table)
# rows = table.find_all('tr')

# # Create a list to store the data for new rows
# new_rows = []

# # Skip the header row
# for row in rows[1:]:
#     cols =  row.find_all('td')
#     language_name=cols[1].get_text()
#     annual_salary=cols[3].get_text()

#     # Append the data for the new row as a dictionary to the list
#     new_rows.append({'Language name': language_name, 'annual average salary': annual_salary})

# # Create a DataFrame from the new rows and concatenate it with the original
# new_df = pd.DataFrame(new_rows)
# Programming_Languages = pd.concat([Programming_Languages, new_df], ignore_index=True)

# # Programming_Languages.drop(index=Programming_Languages.index[0],axis=0,inplace=True)
# Programming_Languages.head(10)

Scrape the `Language name` and `annual average salary`.

In [ ]:
#your code goes here
Programming_Languages = pd.DataFrame(columns=['Language name','annual average salary'])
table = soup.find('table')
# print(table)
rows = table.find_all('tr')
# Skip the header row
for row in rows[1:]:

    cols =  row.find_all('td')
    language_name=cols[1].get_text()
    annual_salary=cols[3].get_text()
    new_row = pd.DataFrame({'Language name': [language_name], 'annual average salary': [annual_salary]})
    Programming_Languages = pd.concat([Programming_Languages, new_row], ignore_index=True)


# Programming_Languages.drop(index=Programming_Languages.index[0],axis=0,inplace=True)
Programming_Languages.head(10)

  Language name annual average salary
0        Python              $114,383
1          Java              $101,013
2             R               $92,037
3    Javascript              $110,981
4         Swift              $130,801
5           C++              $113,865
6            C#               $88,726
7           PHP               $84,727
8           SQL               $84,793
9            Go               $94,082

Save the scrapped data into a file named *popular-languages.csv*

In [ ]:
# your code goes here
Programming_Languages.to_csv('popular-languages.csv', index=False)
print("The Data has been saved into the file popular-languages.csv")

The Data has been saved into the file popular-languages.csv

In [ ]:
df2 = pd.read_csv('popular-languages.csv')
df2.head(10)

  Language name annual average salary
0        Python              $114,383
1          Java              $101,013
2             R               $92,037
3    Javascript              $110,981
4         Swift              $130,801
5           C++              $113,865
6            C#               $88,726
7           PHP               $84,727
8           SQL               $84,793
9            Go               $94,082

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

|  Date (YYYY-MM-DD) |  Version | Changed By  |  Change Description |
|---|---|---|---|
| 2020-10-17  | 0.1  | Ramesh Sannareddy  |  Created initial version of the lab |

 Copyright &copy; 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork928-2022-01-01).